server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: "1115"
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  spring:                            # 新增：发送验证码功能
    mail:
      host: smtp.qq.com              # QQ 邮箱 SMTP 服务器地址
      username: 1341036097@qq.com      # 发件人邮箱 (你的邮箱)
      password: yixsyxuujbdxidaj     # 【注意】这里填获取到的16位授权码，不是QQ密码！
      default-encoding: UTF-8
      properties:
        mail:
          smtp:
            auth: true               # 需要开启认证
            starttls:
              enable: true           # 开启加密传输
              required: true
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug